### ISSUE TITLE
Module Request: Matrox Monarch HD

### ISSUE THREAD

**Issue by AnthonyDabbs** [bitfocus/companion-module-matrox-monarch#1]
**Describe the feature**
Module for the Matrox Monarch HD Hardware Encoder/Recorder. There is a module for the HDX, but the same commands do not apply to the HD

**Is this platform dependent (windows, mac, ..)?**
No

**If documentation is required to implement, do you know where to find it?**
https://www.matrox.com/video/media/pdf/support/monarch_hd/doc/en_Matrox_Monarch_Dev_Tools_Reference_Guide_2_1_1.pdf

**Usecases**
Start Streamer or Recorder or Streamer/Recorder at the same time

**Comment by AnthonyDabbs** [comment]
I know the streaming API Command is 'StartStreaming' and 'StopStreaming'

**Comment by bbredewold** [comment]
@anthman20 Support for the HD is coming very soon now :)
Pull request: #5
Other issue: #3

**Comment by bbredewold** [comment]
Support for HD integrated. Closing.
